<?php
// $Id: rsvp_plaxo.module,v 1.1.2.2 2009/05/26 18:37:09 ulf1 Exp $

/**
 * @module rsvp_plaxo
 * 
 * @package rsvp - A drupal module developed for civicspace - a distribution of drupal.
 * @description Provides functionality to invite people based on your plaxo addressbook
 * @author Ulf Schenk (ulf@schenkunlimited.net)
 *
 */

/**
 * RSVP PLAXO PERMISSIONS
 */
define('RSVP_PERM_INVITE_PLAXO',    'rsvp invite plaxo');

/**
 * Provides the rsvp plaxo permission information for the drupal system.
 *
 * @ingroup rsvp_plaxo
 */
function rsvp_plaxo_perm() {
  return array(RSVP_PERM_INVITE_PLAXO);
}

/**
 * Implementation of hook_menu().
 *
 * @ingroup rsvp_plaxo
 */
function rsvp_plaxo_menu() {

  $connector = new RsvpConnector();
  
  $items = array();

  $items['rsvp/%rsvp/attendees/plaxo/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rsvp_plaxo_add_form', 1, 4),
    'access callback' => 'rsvp_function_invitation_by_invite_access',
    'access arguments' => array($connector, 1, NULL, NULL, RSVP_ACCESS_REPLY, RSVP_PERM_INVITE_PLAXO),
    'weight' => '2',
  );
  
  return $items;
}

function rsvp_plaxo_footer ($main = 0) {
  
  //add javascript to footer only if we are on the right page where you can add guests (rsvp/RID/attendees).
  if ( arg(0) =='rsvp') {
    if ( arg(2) =='attendees') {
  
      $script ='
        <script type="text/javascript" src="http://www.plaxo.com/css/m/js/util.js"></script>  
        <script type="text/javascript" src="http://www.plaxo.com/css/m/js/basic.js"></script>
        <script type="text/javascript" src="http://www.plaxo.com/css/m/js/abc_launcher.js"></script>
    
        <script type="text/javascript"><!--
          function onABCommComplete(data) {
            // data is an array of selected name/email arrays, i.e. [[name1, email1], [name2, email2], ...]
    
            // collect just the emails
            var emails = [];
            for (var i = 0; i < data.length; i++) {
              emails.push(data[i][1]);
            }
    
            // write the list of emails into the following textarea
            var textAreaId = "edit-recipients"; 
            document.getElementById(textAreaId).value = emails.join("\r\n");
          }
          //--></script>';    
      }
    }
  
  return $script;
}


/**
 * Adding a list of plaxo adresses as invitees to the $rsvp.
 *
 * @param $rsvp The rsvp object you want to add the plaxo adresses to.
 * @param $roleid int The role ID.
 *
 * @ingroup rsvp_plaxo
 */
function rsvp_plaxo_add_form(&$form_state, $rsvp, $roleid) {

  if (is_numeric($roleid)) {
    $guestsarray = rsvp_plaxo_function_list($roleid);

    $connector = new RsvpConnector();
    
    $statusarray = rsvp_function_add_guests($rsvp, NULL, $guestsarray, false);

    drupal_set_message('New Guests have been added. Do not forget to send the invitation.');
    
    $content .= theme('rsvp_status', $statusarray);
    drupal_set_message($content);
  }
  
  drupal_goto(rsvp_function_session_parent(NULL, false));
}

/**
 * Implementation of hook_form_alter().
 * 
 * weigth of plugins is always 40
 * 
 * to append the plaxo choice to the attendee form if the permissions are right.
 *
 * @ingroup rsvp_plaxo
 * 
 */
function rsvp_plaxo_form_alter(&$form, $form_state, $form_id) {
	
  if ($form_id == 'rsvp_add_guests_form') {
    $rsvp = $form['rsvp_add_guests_form']['rsvp']['#value'];
	  if ( is_null($rsvp) )
      return;
    
    $connector = new RsvpConnector();
    if (rsvp_function_invitation_by_invite_access($connector, $rsvp, NULL, NULL, RSVP_ACCESS_REPLY, RSVP_PERM_INVITE_PLAXO) == true) {
    
      
      $base = base_path();
      
      // integrate right into the "Add Guests form".
      $form['rsvp_plaxo'] = array(
        '#value' => '<a href="#" onclick="showPlaxoABChooser(\'edit-recipients\', \'/' . $base . '/' . drupal_get_path('module', 'rsvp_plaxo') . '/callback.html\'); return false"><img src="http://www.plaxo.com/images/abc/buttons/add_button.gif" alt="Add from my address book" /></a>',
        '#weight' => 53,
        '#prefix' => '<div class="rsvp_form_content rsvp_add_guests_form_content rsvp_color_inner" style="text-align: right">',
        '#suffix' => '</div>',
//        '#attributes' => array('height' => '40px'),
      );
      
    }
  }
  
}

