<?php
# Copyright (c) 2010 Impressive.media
# Author: Eugen Mayer

require_once('wysiwyg_imageupload.file.inc');
require_once('wysiwyg_imageupload.form.inc');
require_once('wysiwyg_imageupload.ajax.inc');
function wysiwyg_imageupload_menu() {
  $items = array();
  $items['ajax/wysiwyg_imgupl/add/%'] = array(
	  'page callback' => 'drupal_get_form',
    'page arguments' => array('wysiwyg_imageupload_upload_form', 3),
    'access callback' => 'user_access',
    'access arguments' => array('use wysiyg image upload'),
    'type' => MENU_CALLBACK,
  );

  $items['ajax/wysiwyg_imgupl/update/%'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wysiwyg_imageupload_update_form',3,4,5,6),
    'access callback' => 'user_access',
    'access arguments' => array('use wysiyg image upload'),
    'type' => MENU_CALLBACK,
  );

  $items['ajax/wysiwyg_imgupl/upload/%'] = array(
  	'page callback' => '_wysiwyg_imageupload_upload_js',
  	'page arguments' => array(3),
    'access callback' => 'user_access',
    'access arguments' => array('use wysiyg image upload'),
  	'type' => MENU_CALLBACK,
  );

  $items['ajax/wysiwyg_imgupl/showimage/%/%'] = array(
    'page callback' => '_wysiwyg_imageupload_show_image',
    'page arguments' => array(3,4),
    'access callback' => 'user_access',
    'access arguments' => array('use wysiyg image upload'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/settings/wysiwyg_imageupload/settings'] = array (
    'type' => MENU_NORMAL_ITEM,
    'title' => 'WYSIWYG Image upload',
    'description' => 'Configuration options for the WYSIWYG Image upload module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wysiwyg_imageupload_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'wysiwyg_imgupload.admin.inc'
   );

  return $items;
}

/*
 * Implementing the hook_wysiwyg_include_directory
 * This is needed to register our WYSIWYG Plugin
 */
function wysiwyg_imageupload_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'plugins':
      return $type;
  }
}

/*
 * Implementation of hook_perm
 */
function wysiwyg_imageupload_perm() {
  return array('use wysiyg image upload');
}

/*
 * implementation of hook_init
 */
function wysiwyg_imageupload_init() {
  $m = drupal_get_path('module', 'wysiwyg_imageupload');
  drupal_add_css($m.'/plugins/imgupload/imgupload.css');
}

/*
 * Shared with the upload module
 */
function wysiwyg_imageupload_nodeapi(&$node, $op, $teaser) {
  switch ($op) {
    case 'load':
      $output['images'] = _wysiwyg_imageupload_load($node);
      return $output;
    break;
    case 'insert':
    case 'update':
      if (user_access('use wysiyg image upload')) {
        _wysiwyg_imageupload_save($node);
      }
      break;
  }
}

/*
 * Implementation of hook_form_alter
 * Adding jquery_ui_dialog javascript / css definitions to the form
 */
function wysiwyg_imageupload_form_alter(&$form, $form_state, $form_id){
  // Even if the wysiwyg_imageupload button is not activate, we need to load the
  // jquery_ui_dialog preconditions. The user might switch the editor on the node form
  // then we would need it
  if ($form['#id'] == 'node-form' ) {
    jquery_ui_dialog_parent_js();
    $form['#submit'][] = 'wysiwyg_imageupload_form_submit';
  }

  if(strstr($form_state['post']['form_id'],'node_form')) {
    jquery_ui_dialog_parent_js();
  }
}

/*
 * Returns all the image styles to show in the selection
 */
function _wysiwyg_imageupload_get_image_styles() {
  // Must have the format: Descriptive=css_style,Descriptive2=css_style2..
  $settings = variable_get('wysiwyg_imageupload_imgstyles', '');
  $styles = array();
  if($settings != '') {
    foreach(explode(',',$settings) as $style) {
      $style = explode('=',$style);
      $styles[$style[1]] = t($style[0]);
    }
  }
  drupal_alter('wysiwyg_imageupload_image_styles', $styles);
  return $styles;
}

/*
 * Default image preset
 */
function wysiwyg_imageupload_imagecache_default_presets() {
  $presets = array();
  $presets['Original'] = array (
    'presetname' => t('Original size'),
    'actions' => array (),
  );
  $presets['Big'] = array (
    'presetname' => t('Big'),
    'actions' =>
    array (
      0 =>
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' =>
        array (
          'width' => '640',
          'height' => '',
          'upscale' => 0,
        ),
      ),
    ),
  );

  return $presets;
}
