<?php
// $Id: rsvp_buddylist2.module,v 1.1.2.2 2009/03/04 20:09:37 ulf1 Exp $

/**
 * @module rsvp_buddylist2
 * 
 * @package rsvp - A drupal module developed for civicspace - a distribution of drupal.
 * @description Provides functionality to invite people that are part of buddylist2 buddylists
 * @author Ulf Schenk (ulf@schenkunlimited.net)
 *
 */

/**
 * RSVP BUDDYLIST2 PERMISSIONS
 */
define('RSVP_PERM_INVITE_BUDDYLIST2',  'rsvp invite buddylist2');

/**
 * Provides the rsvp buddylist2 permission information for the drupal system.
 *
 * @ingroup rsvp_buddylist2
 */
function rsvp_buddylist2_perm() {
  return array(RSVP_PERM_INVITE_BUDDYLIST2);
}

/**
 * Implementation of hook_menu().
 *
 * @ingroup rsvp_buddylist2
 */
function rsvp_buddylist2_menu() {

  $connector = new RsvpConnector();
  
  $items = array();

  $items['rsvp/%rsvp/attendees/buddylist2/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rsvp_buddylist2_add_form', 1, 4),
    'access callback' => 'rsvp_function_invitation_by_invite_access',
    'access arguments' => array($connector, 1, NULL, NULL, RSVP_ACCESS_REPLY, RSVP_PERM_INVITE_BUDDYLIST2),
    'weight' => '2',
  );

  return $items;
}

/**
 * Adding a list of buddylist2 buddylist members as invitees to the $rsvp.
 *
 * @param $rsvp The rsvp object you want to add the buddylist members to.
 * @param $bid int The buddylist ID.
 * @return string list of subscribers.
 *
 * @ingroup rsvp_buddylist2
 */
function rsvp_buddylist2_add_form(&$form_state, $rsvp, $bid) {

  if (is_numeric($bid)) {
    $guestsarray = rsvp_buddylist2_function_list($bid, $type);
    
    $connector = new RsvpConnector();
    
    $statusarray = rsvp_function_add_guests($rsvp, NULL, $guestsarray, false);
    
    if (count($statusarray['success_add']) > 0)
      drupal_set_message('New Guests have been added. Do not forget to send the invitation.');
 
    $content .= theme('rsvp_status', $statusarray);
    drupal_set_message($content);
    
  }
  
  drupal_goto(rsvp_function_session_parent(NULL, false));
    
}

/**
 * Returns a list with available buddylists that can be added to the invitation.
 *
 * @param $rsvp The RSVP object.
 * @return a list with links to buddylists that can be added to the invitation.
 *
 * @ingroup rsvp_buddylist2
 */
function rsvp_buddylist2_linklist($rsvp) {

  $links = array();
  
  if (module_exists('buddylist_api')) {
    if (user_is_anonymous())
      return $links;
      
    global $user; 

    $my_relationships = buddylist_api_load_relationships($user->uid);

    //filter the relationtypes from the relationships
    if (is_array($my_relationships)) {
      foreach ($my_relationships as $relship) {
        $groups[$relship->rtid] = $relship->rid;
      }
    }
    else {
      $groups[$my_relationships->rtid] = $my_relationships->rid;
    	
    }
    
    
    foreach ($groups as $rtid => $rid) {
      $rttype = buddylist_api_rtype_load($rtid);
   	
      $links[] = l($rttype->name, 'rsvp/'. $rsvp->rid .'/attendees/buddylist2/'. $rtid, array('attributes' => array('title' => t('Add %term members to this invitation', array('%term' => $rttype->name)))));
    }
    
  }
  
  return $links;  
}

/**
 * Implementation of hook_form_alter().
 * 
 * weigth of plugins is always 40
 * 
 * to append the buddylist2 choice to the attendee form if the permissions are right.
 * 
 * @ingroup rsvp_buddylist2
 * 
 */
function rsvp_buddylist2_form_alter(&$form, $form_state, $form_id) {

  
  
  if ($form_id == 'rsvp_add_guests_form') {
	  $rsvp = $form['rsvp_add_guests_form']['rsvp']['#value'];
    if ( is_null($rsvp) )
      return;
    
    $connector = new RsvpConnector();
    if (rsvp_function_invitation_by_invite_access($connector, $rsvp, NULL, NULL, RSVP_ACCESS_REPLY, RSVP_PERM_INVITE_BUDDYLIST2) == true) {
    
      $links = rsvp_buddylist2_linklist($rsvp);
      //$title = t('Relationships');
      
      $itemlist = theme('item_list', $links, $title);
     
      $form['rsvp_add_guests']['rsvp_buddylist2'] = array(
        '#weight' => 40,
        '#value' => '<div class="rsvp_form rsvp_add_guests_form rsvp_color_border rsvp_color_inner">',
        '#suffix' => '</div>',
      );

      $form['rsvp_add_guests']['rsvp_buddylist2']['header'] = array(
        '#value' => t('You may invite members by relationship'),
        '#prefix' => '<div class="rsvp_form_header rsvp_add_guests_form_header rsvp_color_outer">',
        '#suffix' => '</div>',
      );
      
      $form['rsvp_add_guests']['rsvp_buddylist2']['list'] = array(
        '#value' => $itemlist,
        '#prefix' => '<div class="rsvp_form_content rsvp_add_guests_form_content rsvp_color_inner">',
        '#suffix' => '</div>',
      
      );
      
    }
  }
  
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////

/*
* @ingroup rsvp_buddylist2_action
* 
* Implementation of hook_action_info()
*/
/*
function rsvp_buddylist2_action_info() {
  
  return array(
      'rsvp_buddylist2_add_guests_action' => array(
        'description' => t('RSVP: Add buddylist2 group members to invitation'),
        'type' => 'node',
        'configurable' => FALSE,
        'hooks' => array(
          'any' => TRUE,
        ),
      ),
  );
}
*/

/**
 * A nonconfigurable Drupal action. Adds guests based on buddylist2 group to an invitation (host permissions) and send the invitation message
 *   hook = any
 *
 *   Required contexts:
 *    $context['rid'] The invitation id you want to add guests to.
 *    $context['bid'] The Buddylist id.
 *    $context['send_rsvp'] Boolean also send the invitations or just add the guests to the invitation.
 *
 * @ingroup rsvp_buddylist2_actions
 * 
 */
function rsvp_buddylist2_add_guests_action(&$object, $context = array()) {

  if ((!isset($context['rid'])) || (!isset($context['bid'])) || (!isset($context['send_rsvp']))  ) {
    return false;
  }

  rsvp_buddylist2_api_add_guests($context['rid'], NULL, $context['bid'], $context['send_rsvp']);
} 

/**
 * Adds a number of guests based on buddylist2 buddylist to an invitation(rsvp) and sends out the invitations
 * 
 * The function requires the correct user permissions.
 * 
 * @ingroup rsvp_buddylist2_api
 * 
 * @param $rid The Id of the rsvp instance.
 * @param $hash The hash of the invitation object of the user who adds the invitees, 
 *        or NULL if the rsvp owner adds the invitees.
 * @param $bid The id of the buddylist.
 * @param $send_rsvp Boolean Also send the invitations or just add the guests to the invitation.
 */
function rsvp_buddylist2_api_add_guests($rid, $hash, $bid, $send_rsvp) {
  
  $invite = NULL;
  
  if(!isnull($rid)) {
    $rsvp = rsvp_function_load_rsvp($rid);
    if ($rsvp == false)
      return false;
  }
  
  if(!isnull($hash)) {
    $invite = rsvp_function_load_invitation_hash($hash);
    if ($invite == false)
      return false;
  }
  
  $connector = new RsvpConnector();

  $perm_add = rsvp_function_invitation_by_invite_access($connector, $rsvp, NULL, NULL, RSVP_ACCESS_EDIT, RSVP_PERM_INVITE_BUDDYLIST2);
  if ($perm_add == true) {
    $guestarray = rsvp_buddylist2_function_list($bid);
    rsvp_function_add_invitees($rsvp, $invite, $guestsarray, $send_rsvp);
    watchdog('action', 'Added invitees from buddylist2 %bid to invitation %rsvp_name(%rid) successfully.', array('%rsvp_name' => $rsvp->name, '%rid' => $rsvp->rid, '%bid' => $bid)); 
  }
}


/**
 * Extracting a list of buddylist2 group members.
 *
 * The function requires the correct user permissions.
 *
 *
 * @param $bid int The Buddylist ID.
 * @return array of useremails.
 *
 * @ingroup rsvp_buddylist2_functions
 */
function rsvp_buddylist2_function_list($bid) {

  $guestsarray = array();
  
  if (is_numeric($bid)) {
    global $user;
    
    $relationships = buddylist_api_load_relationships($bid, 'rtid');
        
    global $user;
  
    foreach ($relationships as $rel) {
      $requester = user_load($rel->requester_id);
      $requestee = user_load($rel->requestee_id);
    
      if (($requester != false) && ($requester->uid != $user->uid))
        $guestsarray[] = $requester->name;

      if (($requestee != false)  && ($requestee->uid != $user->uid))
        $guestsarray[] = $requestee->name;
    }
  }

  
  return $guestsarray;  
}

