<?php
// $Id: rsvp_roles.module,v 1.1.2.3 2009/08/27 16:03:58 ulf1 Exp $

/**
 * @module rsvp_roles
 * 
 * @package rsvp - A drupal module developed for civicspace - a distribution of drupal.
 * @description Provides functionality to invite users based on their drupal roles
 * @author crunchywelch (welch@advomatic.com)
 * @author Omar Abdel-Wahab (owahab@gmail.com)
 * @author Ulf Schenk (ulf@schenkunlimited.net)
 *
 */

/**
 * RSVP ROLE PERMISSIONS
 */
define('RSVP_PERM_INVITE_ROLE',    'rsvp invite role');

/**
 * Provides the rsvp roles permission information for the drupal system.
 *
 * @ingroup rsvp_roles
 */
function rsvp_roles_perm() {
  return array(RSVP_PERM_INVITE_ROLE);
}

/**
 * Implementation of hook_menu().
 *
 * @ingroup rsvp_roles
 */
function rsvp_roles_menu() {

  $connector = new RsvpConnector();
  
  $items = array();

  $items['rsvp/%rsvp/attendees/role/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rsvp_roles_add_form', 1, 4),
    'access callback' => 'rsvp_function_invitation_by_invite_access',
    'access arguments' => array($connector, 1, NULL, NULL, RSVP_ACCESS_REPLY, RSVP_PERM_INVITE_ROLE),
    'weight' => '2',
  );
  
  return $items;
}

/**
 * Adding a list of role members as invitees to the $rsvp.
 *
 * @param $rsvp The rsvp object you want to add the role members to.
 * @param $roleid int The role ID.
 *
 * @ingroup rsvp_roles
 */
function rsvp_roles_add_form(&$form_state, $rsvp, $roleid) {

  if (is_numeric($roleid)) {
    $guestsarray = rsvp_roles_function_list($roleid);

    $connector = new RsvpConnector();
    
    $statusarray = rsvp_function_add_guests($rsvp, NULL, $guestsarray, false);

    if (count($statusarray['success_add']) > 0)
      drupal_set_message('New Guests have been added. Do not forget to send the invitation.');
    
    $content .= theme('rsvp_status', $statusarray);
    drupal_set_message($content);
  }
  
  drupal_goto(rsvp_function_session_parent(NULL, false));
}

/**
 * Returns a list with available roles that can be added to the invitation.
 *
 * @param $rsvp The RSVP object.
 * @return a list with links to roles that can be added to the invitation.
 *
 * @ingroup rsvp_roles
 */
function rsvp_roles_linklist($rsvp) {

  $links = array();

  foreach (user_roles(TRUE) as $rid => $role) {
    $links[] = l($role, 'rsvp/'. $rsvp->rid .'/attendees/role/'. $rid, array('attributes' => array('title' => t('Add %role members to this invitation', array('%role' => $role)))));
  }
  
  return $links;  
}

/**
 * Implementation of hook_form_alter().
 * 
 * weigth of plugins is always 40
 * 
 * to append the roles choice to the attendee form if the permissions are right.
 *
 * @ingroup rsvp_roles
 * 
 */
function rsvp_roles_form_alter(&$form, $form_state, $form_id) {

  
  
  if ($form_id == 'rsvp_add_guests_form') {
    $rsvp = $form['rsvp_add_guests_form']['rsvp']['#value'];
	  if ( is_null($rsvp) )
      return;
    
    $connector = new RsvpConnector();
    if (rsvp_function_invitation_by_invite_access($connector, $rsvp, NULL, NULL, RSVP_ACCESS_REPLY, RSVP_PERM_INVITE_ROLE) == true) {
    
      $links = rsvp_roles_linklist($rsvp);
      //$title = t('Roles');
      
      $itemlist = theme('item_list', $links, $title);
     
      $form['rsvp']['rsvp_roles'] = array(
        '#weight' => 40,
        '#value' => '<div class="rsvp_form rsvp_add_guests_form rsvp_color_border rsvp_color_inner">',
        '#suffix' => '</div>',
      );

      $form['rsvp']['rsvp_roles']['header'] = array(
        '#value' => t('You may invite members by system roles'),
        '#prefix' => '<div class="rsvp_form_header rsvp_add_guests_form_header rsvp_color_outer">',
        '#suffix' => '</div>',
      
      );
      
      $form['rsvp']['rsvp_roles']['list'] = array(
        '#value' => $itemlist,
        '#prefix' => '<div class="rsvp_form_content rsvp_add_guests_form_content rsvp_color_inner">',
        '#suffix' => '</div>',
      );
      
      
    }
  }
  
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////

/*
* @ingroup rsvp_roles_action
* 
* Implementation of hook_action_info()
*/
/*
function rsvp_roles_action_info() {
  
  return array(
      'rsvp_roles_add_guests_action' => array(
        'description' => t('RSVP: Add users of a role to invitation'),
        'type' => 'node',
        'configurable' => FALSE,
        'hooks' => array(
          'any' => TRUE,
        ),
      ),
  );
}
*/

/**
 * A nonconfigurable Drupal action. Adds guests based on a role to an invitation (host permissions) and send the invitation message
 *   hook = any
 *
 *   Required contexts:
 *    $context['rid'] The invitation id you want to add guests to.
 *    $context['roleid'] The role id.
 *    $context['send_rsvp'] Boolean also send the invitations or just add the guests to the invitation.
 *
 * @ingroup rsvp_roles_actions
 *
 *
 */
function rsvp_roles_add_guests_action(&$object, $context = array()) {

  if ((!isset($context['rid'])) || (!isset($context['roleid'])) || (!isset($context['send_rsvp']))  ) {
    return false;
  }

  rsvp_roles_api_add_guests($context['rid'], NULL, $context['roleid'], $context['send_rsvp']);
} 

/**
 * Adds a number of guests based on role to an invitation(rsvp) and sends out the invitations
 * 
 * The function requires the correct user permissions.
 * 
 * @ingroup rsvp_roles_api
 * 
 * @param $rid The Id of the rsvp instance.
 * @param $hash The hash of the invitation object of the user who adds the invitees, 
 *        or NULL if the rsvp owner adds the invitees.
 * @param $roleid The id of the role.
 * @param $send_rsvp Boolean Also send the invitations or just add the guests to the invitation.
 */
function rsvp_roles_api_add_guests($rid, $hash, $roleid, $send_rsvp) {
  
  $invite = NULL;
  
  if(!isnull($rid)) {
    $rsvp = rsvp_function_load_rsvp($rid);
    if ($rsvp == false)
      return false;
  }
  
  if(!isnull($hash)) {
    $invite = rsvp_function_load_invitation_hash($hash);
    if ($invite == false)
      return false;
  }
  
  $connector = new RsvpConnector();

  $perm_add = rsvp_function_invitation_by_invite_access($connector, $rsvp, NULL, NULL, RSVP_ACCESS_EDIT, RSVP_PERM_INVITE_ROLE);
  if ($perm_add == true) {
    $guestarray = rsvp_roles_function_list($nid);
    rsvp_function_add_invitees($rsvp, $invite, $guestsarray, $send_rsvp);
    watchdog('action', 'Added members from role %roleid to invitation %rsvp_name(%rid) successfully.', array('%rsvp_name' => $rsvp->name, '%rid' => $rsvp->rid, '%roleid' => $roleid)); 
  }
}


/**
 * Extracting members for a specific role.
 *
 * The function requires the correct user permissions.
 *
 *
 * @param $roleid int The role ID.
 * @return array of usernames.
 *
 * @ingroup rsvp_roles_functions
 */
function rsvp_roles_function_list($roleid) {

  $guestsarray = array();
	
  if (is_numeric($roleid)) {
    // if the requested role is authenticated, no records will be returned from
    // normal query
    if ($roleid == 2) {
      $query = db_query('SELECT name FROM {users} ORDER BY uid DESC');
    }
    else {
      $query = db_query('SELECT name FROM {users} u INNER JOIN {users_roles} ur ON u.uid = ur.uid WHERE ur.rid = %d ORDER BY u.uid DESC', $roleid);
    }
    
    while ($u = db_fetch_object($query)) {
    	if (!empty($u))
        $guestsarray[] = $u->name;
    }
  }
  
  return $guestsarray;  
}

