<?php
// $Id: jquery_ui_dialog.module,v 1.1.2.7 2010/03/04 14:36:41 eugenmayer Exp $

# Copyright (c) 2010 Impressive.media
# Author: Eugen Mayer

function jquery_ui_dialog_parent_js() {
  static $processed;
  // Make sure external resources are not included more than once.
  if ($processed === true) {
    return;
  }
  $processed = TRUE;

  jquery_ui_add(array('ui.dialog', 'ui.draggable'));
  $m = drupal_get_path('module', 'jquery_ui_dialog');
  drupal_add_css($m.'/css/jquery_ui_dialog-dialog/jquery_ui_dialog.css');
  drupal_add_css($m .'/css/jquery_ui_dialog.main.css');
  drupal_add_js($m .'/js/jquery_ui_dialog_parent.js');
}

function jquery_ui_dialog_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['page']) && isset($theme_registry['page']['theme paths'])) {
    $module_path = drupal_get_path('module', 'jquery_ui_dialog');
    array_unshift($theme_registry['page']['theme paths'], $module_path);
    array_unshift($theme_registry['page']['preprocess functions'], 'jquery_ui_dialog_pre_preprocess_page');
  }
}

function jquery_ui_dialog_child_js() {
  $m = drupal_get_path('module', 'jquery_ui_dialog');
  drupal_add_js($m .'/js/jquery_ui_dialog_child.js');
  module_invoke_all('jquery_ui_child_loading');
  $GLOBALS['jquery_ui_dialog_page_template'] = TRUE;
}

/**
 * Preprocess template variables for page.tpl.php - step 1.
 *
 * Performance enhancement: prevent template_preprocess_page() from generating
 * sidebar blocks when a modal frame has been requested.
 */
function jquery_ui_dialog_pre_preprocess_page(&$variables) {
  if (!empty($GLOBALS['jquery_ui_dialog_page_template'])) {
    $variables['show_blocks'] = FALSE;
  }
}

/**
 * Preprocess template variables for page.tpl.php - step 2.
 *
 * Now that we have altered the registry entry for theme('page'), we can tell
 * theme() to use a different template file name when we need to render a child
 * window.
 */
function jquery_ui_dialog_preprocess_page(&$variables) {
  if (!empty($GLOBALS['jquery_ui_dialog_page_template'])) {
    if (!isset($variables['template_files'])) {
      $variables['template_files'] = array();
    }
    array_unshift($variables['template_files'], 'jquery_ui_dialog-page');
  }
}